### ISSUE TITLE
查看合约部署详情报错

### ISSUE THREAD

**Issue by Lsw931102** [Conflux-Chain/conflux-portal#167]
![image](https://user-images.githubusercontent.com/13031383/85937213-05810180-b934-11ea-826e-194b127e3693.png)
![image](https://user-images.githubusercontent.com/13031383/85937221-1a5d9500-b934-11ea-9294-38e6f4f15a10.png)

点击图一“合约部署”查看部署详情会报图二的错误，报错详情如下：

TypeError: Cannot read property 'toLowerCase' of undefined
    at chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui.js:1:2795185
    at Array.find (<anonymous>)
    at l (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui.js:1:2795175)
    at Function.mapToProps (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui.js:1:2795308)
    at r (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1142504)
    at Function.r.mapToProps (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1142640)
    at r (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1142504)
    at chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1141348
    at chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1134748
    at Object.useMemo (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:994009)
    at useMemo (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1281849)
    at S (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1134692)
    at ha (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:989842)
    at Qa (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:998058)
    at Ka (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:997877)
    at Xa (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:997596)
    at ks (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1038519)
    at Mu (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1020652)
    at ju (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1020577)
    at xu (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1017917)
    at chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:976247
    at n.unstable_runWithPriority (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1295540)
    at Xi (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:975956)
    at Ji (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:976192)
    at Qi (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:976127)
    at se (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:1045179)
    at Cn (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui-libs.js:1:959778)
    at HTMLDocument.u (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/ui.js:1:254531)

**Comment by yqrashawn** [comment]
你好, 请问使用的是哪个版本的 ConfluxPortal? 目前在本地没办法复现这个错误.

**Comment by yqrashawn** [comment]
fixed in 0.3.5
