### ISSUE TITLE
Signing with localhost:12537 inexplicably changes txns from net999 to net2999 (?)

### ISSUE THREAD

**Issue by DanBurton** [Conflux-Chain/conflux-portal#352]
**Describe the bug**
When I attempt to sign & send a transaction using the built-in network settings for Localhost 12537, after clicking "confirm", it fails to sign the transaction with an error about "net2999", even though the to/from addresses in my transaction are both "net999".

**To Reproduce**

* Run a conflux devnet on localhost:12537 with netId 999
* Fund an account and add that account to Conflux Portal
* Open this html in a browser with ConfluxPortal installed:

```html
<html>
<head>
<script type="text/javascript">
async function transfer(from, to, value) {
  value = '0x' + BigInt(value).toString(16)
  console.log({from, to, value});
  return new Promise((resolve, reject) => {
    conflux.sendAsync({
      method: 'cfx_sendTransaction',
      params: [{from, to, value}],
      from,
      value,
    }, (err, data) => {
      if (err) { reject(err); } else { resolve(data); }
    })
  });
}

async function go () {
  const from = (await conflux.enable())[0];
  const to = document.getElementById('to').value || from; // default: send to self
  const amt = parseInt(document.getElementById('amt').value) || 10; // CFX
  const value = amt + '0'.repeat(18); // Drip

  await transfer(from, to, value);
}
</script>
</head>
<body>
  <input id="amt" type="number" value=10 style="width: 3em" /> CFX
  to <input id="to" placeholder="paste address here" />
  <button onClick="go()">Send</button>
</body>
</html>
```

* Choose "Localhost 12537" from the ConfluxPortal network options
* Select any address that you want to send devnet CFX to
* Click "Send"
* Choose the address to send from, if prompted
* Click "Confirm" from the ConfluxPortal dialogue

**Expected behavior**
`sendAsync` should transfer the funds on the devnet running at localhost:12537. (It works on TestNet.)

**Browser details (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Firefox 89.0.2
 - ConfluxPortal Version: 0.6.8

**Additional context**

Sometimes it will not let you click Confirm, claiming that there is no balance (even on accounts with a balance on your localhost devnet.) Other times, it will fail with the following error:

```
ConfluxPortal - RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"message":"Invalid parameters: address","data":"\"network prefix unexpected: ours net999, got net2999\"","stack":"Error: Invalid parameters: address\n    at s (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/background.js:1:398023)\n    at Object.internal (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/background.js:1:398412)\n    at l (chrome-extension://opafkgfpaamecojfkaialabagfofilmg/background.js:1:393516)\n    at chrome-extension://opafkgfpaamecojfkaialabagfofilmg/background.js:1:392727"}}' 
```

This is nonsense. See the output of the `console.log` included in the html snippet above, which will indicate that the transaction being sent is for `net999` as it should be.

**Comment by DanBurton** [comment]
Note that if you create a "custom rpc" network option, and point it at `127.0.0.1:12537` (it will not allow you to do `localhost:12537`), then everything works as expected. I have no idea why the built-in localhost:12537 settings are misbehaving.
